### ISSUE TITLE
Add project to test PyPI

### ISSUE THREAD

**Issue by tim-schilling** [django-commons/django-typer#126]
The Django Commons release action supports testing the release of the package to test.pypi.org. This requires the project to exist there which [requires a manual upload](https://packaging.python.org/en/latest/tutorials/packaging-projects/#uploading-the-distribution-archives).

The test release GHA code can be found here: https://github.com/django-commons/django-commons-playground/blob/main/.github/workflows/release.yml#L97

**Comment by bckohan** [comment]
done: https://test.pypi.org/project/django-typer/
